#!/bin/bash

# Check if a directory was provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 directory"
  exit 1
fi

# Loop through all .md and .pdf files in the current directory and replace spaces with underscore
for file in "$1"/*.md "$1"/md/*.md "$1"/*.pdf; do
  # Check if the file exists (in case there are no .md or .pdf files)
  if [[ -e "$file" ]]; then
    # Replace spaces with underscores in the filename
    new_file=$(echo "$file" | tr ' ' '_')
    # Rename the file
    mv "$file" "$new_file"
  fi
done
