#!/bin/bash

# Check if a directory was provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 directory"
  exit 1
fi

# Iterate over all .pdf files in the directory $1
directory=$1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

for file in "$directory"/*.pdf; do
#$echo "processing $file"
    # Check if the file exists
    if [[ -f "$file" ]]; then
        # Replace spaces with underscores in the filename
        new_file=$(echo "$file" | tr ' ' '_')
        echo "after removing spaces $new_file \n"
        # Rename the file
        mv "$file" "$new_file"
        
        # Run the notate script on the renamed file
        $SCRIPT_DIR/run1.txt "$new_file"
    fi
done